### ISSUE TITLE
[BUG] got multiple values for keyword argument 'client_id'

### ISSUE THREAD

**Issue by arkpoah** [salt-extensions/saltext-azurerm#48]
**Description**
I'm trying using azurerm with Salt 3006.7 via salt-cloud, but always same error is coming : 
`[ERROR   ] There was a profile error: azure.identity._credentials.managed_identity.ManagedIdentityCredential() got multiple values for keyword argument 'client_id'`

**Setup**
-  VM running on Azure
-  onedir packaging

saltext-azurem installed via `/opt/saltstack/salt/bin/pip` like mentionned in https://github.com/saltstack/salt/issues/65433, otherwise via `salt-pip` I get `module not load error`

Here's pip packages installed
```
# salt-pip list
Package                     Version
--------------------------- ---------
adal                        1.2.7
azure-batch                 12.0.0
azure-common                1.1.28
azure-core                  1.24.2
azure-graphrbac             0.61.1
azure-identity              1.10.0
azure-keyvault              4.2.0
azure-keyvault-certificates 4.7.0
azure-keyvault-keys         4.8.0
azure-keyvault-secrets      4.7.0
azure-mgmt-authorization    2.0.0
azure-mgmt-batch            16.2.0
azure-mgmt-compute          27.1.0
azure-mgmt-core             1.3.2
azure-mgmt-dns              8.0.0
azure-mgmt-keyvault         10.1.0
azure-mgmt-monitor          6.0.1
azure-mgmt-msi              6.0.1
azure-mgmt-network          20.0.0
azure-mgmt-privatedns       1.0.0
azure-mgmt-resource         21.1.0
azure-mgmt-storage          21.0.0
azure-mgmt-subscription     3.0.0
azure-mgmt-web              6.1.0
azure-nspkg                 3.0.2
azure-storage-blob          12.12.0
azure-storage-common        2.1.0
azure-storage-file          2.1.0
azure-storage-nspkg         3.1.0
azure-storage-queue         12.3.0
certifi                     2023.7.22
cffi                        1.14.6
charset-normalizer          3.2.0
cheroot                     8.5.2
CherryPy                    18.6.1
contextvars                 2.4
cryptography                42.0.3
distlib                     0.3.7
distro                      1.5.0
elastic-transport           8.10.0
elasticsearch               8.11.0
envtpl                      0.7.2
filelock                    3.13.1
idna                        3.2
immutables                  0.15
importlib-metadata          6.0.0
isodate                     0.6.1
jaraco.classes              3.2.1
jaraco.collections          3.4.0
jaraco.functools            2.0
jaraco.text                 3.5.1
Jinja2                      3.1.3
jmespath                    1.0.1
looseversion                1.0.2
Mako                        1.2.4
MarkupSafe                  2.1.2
more-itertools              5.0.0
msal                        1.27.0
msal-extensions             1.1.0
msgpack                     1.0.2
msrest                      0.7.1
msrestazure                 0.6.4
oauthlib                    3.2.2
packaging                   22.0
pip                         23.3.2
platformdirs                4.1.0
portalocker                 2.8.2
portend                     2.4
psutil                      5.8.0
pycparser                   2.21
pycryptodomex               3.19.1
pygit2                      1.11.1
PyJWT                       2.8.0
pyOpenSSL                   24.0.0
PySocks                     1.7.1
python-dateutil             2.8.1
python-gnupg                0.4.8
pytz                        2022.1
PyYAML                      6.0.1
pyzmq                       23.2.0
relenv                      0.15.1
requests                    2.31.0
requests-oauthlib           1.3.1
rpm-vercmp                  0.1.2
salt                        3006.7
saltext.azurerm             4.0.1
setproctitle                1.3.2
setuptools                  68.2.2
six                         1.16.0
supervisor                  4.2.5
tempora                     4.1.1
timelib                     0.2.5
typing_extensions           4.10.0
urllib3                     1.26.18
virtualenv                  20.25.0
wheel                       0.42.0
zc.lockfile                 1.4
zipp                        3.6.0
```
My provider configuration
```
# cat /etc/salt/cloud.providers.d/azure.conf 
azurearm-FranceCentral:
  driver: azurerm
  master: salt-syndic1-azr-pilot-francecentral-xxxxx
  subscription_id: xxxxxxxxx
  tenant: xxxxxxxxxx
  client_id: xxxxxxxxxxx
  secret: xxxxxxxxx
  location: FranceCentral
  storage_account: xxxxxx
  storage_key: xxxxxxxx
  ssh_username: xxxxxx
  ssh_password: xxxxxxx

```
**Steps to Reproduce the behavior**
When I run some salt-cloud command, I always get this
```
# salt-cloud --list-locations azurearm-FranceCentral -l debug
[DEBUG   ] Reading configuration from /etc/salt/cloud
[DEBUG   ] Reading configuration from /etc/salt/master
[DEBUG   ] Including configuration from '/etc/salt/master.d/00-general.conf'
[DEBUG   ] Reading configuration from /etc/salt/master.d/00-general.conf
[DEBUG   ] Including configuration from '/etc/salt/master.d/05-syndic.conf'
[DEBUG   ] Reading configuration from /etc/salt/master.d/05-syndic.conf
[DEBUG   ] Including configuration from '/etc/salt/master.d/10-jobs.conf'
[DEBUG   ] Reading configuration from /etc/salt/master.d/10-jobs.conf
[DEBUG   ] Including configuration from '/etc/salt/master.d/20-vault.conf'
[DEBUG   ] Reading configuration from /etc/salt/master.d/20-vault.conf
[DEBUG   ] Including configuration from '/etc/salt/master.d/22-gitfs.conf'
[DEBUG   ] Reading configuration from /etc/salt/master.d/22-gitfs.conf
[DEBUG   ] Including configuration from '/etc/salt/master.d/23-pillar.conf'
[DEBUG   ] Reading configuration from /etc/salt/master.d/23-pillar.conf
[DEBUG   ] Including configuration from '/etc/salt/master.d/24-cache.conf'
[DEBUG   ] Reading configuration from /etc/salt/master.d/24-cache.conf
[DEBUG   ] Including configuration from '/etc/salt/master.d/30-reactor.conf'
[DEBUG   ] Reading configuration from /etc/salt/master.d/30-reactor.conf
[DEBUG   ] Including configuration from '/etc/salt/master.d/40-api.conf'
[DEBUG   ] Reading configuration from /etc/salt/master.d/40-api.conf
[DEBUG   ] Including configuration from '/etc/salt/master.d/50-auth.conf'
[DEBUG   ] Reading configuration from /etc/salt/master.d/50-auth.conf
[DEBUG   ] Including configuration from '/etc/salt/master.d/60-peer_run.conf'
[DEBUG   ] Reading configuration from /etc/salt/master.d/60-peer_run.conf
[DEBUG   ] Using cached minion ID from /etc/salt/minion_id: salt-build-insideboard.internal.cloudapp.net
[DEBUG   ] Missing configuration file: /etc/salt/cloud.providers
[DEBUG   ] Including configuration from '/etc/salt/cloud.providers.d/azure.conf'
[DEBUG   ] Reading configuration from /etc/salt/cloud.providers.d/azure.conf
[DEBUG   ] Reading configuration from /etc/salt/cloud.profiles
[DEBUG   ] Including configuration from '/etc/salt/cloud.profiles.d/client.conf'
[DEBUG   ] Reading configuration from /etc/salt/cloud.profiles.d/client.conf
[DEBUG   ] Including configuration from '/etc/salt/cloud.profiles.d/proxy.conf'
[DEBUG   ] Reading configuration from /etc/salt/cloud.profiles.d/proxy.conf
[DEBUG   ] Including configuration from '/etc/salt/cloud.profiles.d/sensu.conf'
[DEBUG   ] Reading configuration from /etc/salt/cloud.profiles.d/sensu.conf
[WARNING ] Insecure logging configuration detected! Sensitive data may be logged.
[DEBUG   ] Configuration file path: /etc/salt/cloud
[INFO    ] salt-cloud starting
[DEBUG   ] Reading configuration from /etc/salt/minion
[DEBUG   ] Including configuration from '/etc/salt/minion.d/_schedule.conf'
[DEBUG   ] Reading configuration from /etc/salt/minion.d/_schedule.conf
[DEBUG   ] Including configuration from '/etc/salt/minion.d/smtp.conf'
[DEBUG   ] Reading configuration from /etc/salt/minion.d/smtp.conf
[DEBUG   ] Reading configuration from /etc/salt/minion
[DEBUG   ] Including configuration from '/etc/salt/minion.d/_schedule.conf'
[DEBUG   ] Reading configuration from /etc/salt/minion.d/_schedule.conf
[DEBUG   ] Including configuration from '/etc/salt/minion.d/smtp.conf'
[DEBUG   ] Reading configuration from /etc/salt/minion.d/smtp.conf
[DEBUG   ] The functions from module 'aggregation' are being loaded from the provided __all__ attribute
[DEBUG   ] Marking 'ifelse' as a jinja global
[DEBUG   ] Marking 'strftime' as a jinja filter
[DEBUG   ] Marking 'date_format' as a jinja filter
[DEBUG   ] Marking 'base64_encode' as a jinja filter
[DEBUG   ] Marking 'base64_decode' as a jinja filter
[DEBUG   ] Marking 'md5' as a jinja filter
[DEBUG   ] Marking 'sha1' as a jinja filter
[DEBUG   ] Marking 'sha256' as a jinja filter
[DEBUG   ] Marking 'sha512' as a jinja filter
[DEBUG   ] Marking 'hmac' as a jinja filter
[DEBUG   ] Marking 'hmac_compute' as a jinja filter
[DEBUG   ] Marking 'random_hash' as a jinja filter
[DEBUG   ] Marking 'rand_str' as a jinja filter
[DEBUG   ] Marking 'file_hashsum' as a jinja filter
[DEBUG   ] Marking 'http_query' as a jinja filter
[DEBUG   ] Marking 'raise' as a jinja global
[DEBUG   ] Marking 'match' as a jinja test
[DEBUG   ] Marking 'equalto' as a jinja test
[DEBUG   ] Marking 'skip' as a jinja filter
[DEBUG   ] Marking 'sequence' as a jinja filter
[DEBUG   ] Marking 'to_bool' as a jinja filter
[DEBUG   ] Marking 'indent' as a jinja filter
[DEBUG   ] Marking 'tojson' as a jinja filter
[DEBUG   ] Marking 'quote' as a jinja filter
[DEBUG   ] Marking 'regex_escape' as a jinja filter
[DEBUG   ] Marking 'regex_search' as a jinja filter
[DEBUG   ] Marking 'regex_match' as a jinja filter
[DEBUG   ] Marking 'regex_replace' as a jinja filter
[DEBUG   ] Marking 'uuid' as a jinja filter
[DEBUG   ] Marking 'unique' as a jinja filter
[DEBUG   ] Marking 'min' as a jinja filter
[DEBUG   ] Marking 'max' as a jinja filter
[DEBUG   ] Marking 'avg' as a jinja filter
[DEBUG   ] Marking 'union' as a jinja filter
[DEBUG   ] Marking 'intersect' as a jinja filter
[DEBUG   ] Marking 'difference' as a jinja filter
[DEBUG   ] Marking 'symmetric_difference' as a jinja filter
[DEBUG   ] Marking 'method_call' as a jinja filter
[DEBUG   ] Marking 'yaml_dquote' as a jinja filter
[DEBUG   ] Marking 'yaml_squote' as a jinja filter
[DEBUG   ] Marking 'yaml_encode' as a jinja filter
[DEBUG   ] The functions from module 'args' are being loaded by dir() on the loaded module
[DEBUG   ] The functions from module 'asynchronous' are being loaded by dir() on the loaded module
[DEBUG   ] The functions from module 'atomicfile' are being loaded by dir() on the loaded module
[DEBUG   ] The functions from module 'aws' are being loaded by dir() on the loaded module
[DEBUG   ] The functions from module 'azurearm' are being loaded by dir() on the loaded module
[DEBUG   ] The functions from module 'beacons' are being loaded by dir() on the loaded module
[DEBUG   ] The functions from module 'boto_elb_tag' are being loaded by dir() on the loaded module
[DEBUG   ] The functions from module 'cache' are being loaded by dir() on the loaded module
[DEBUG   ] The functions from module 'channel' are being loaded by dir() on the loaded module
[DEBUG   ] The functions from module 'cloud' are being loaded by dir() on the loaded module
[DEBUG   ] The functions from module 'color' are being loaded by dir() on the loaded module
[DEBUG   ] The functions from module 'compat' are being loaded by dir() on the loaded module
[DEBUG   ] The functions from module 'configcomparer' are being loaded by dir() on the loaded module
[DEBUG   ] The functions from module 'configparser' are being loaded by dir() on the loaded module
[DEBUG   ] The functions from module 'context' are being loaded by dir() on the loaded module
[DEBUG   ] The functions from module 'crypt' are being loaded by dir() on the loaded module
[DEBUG   ] The functions from module 'ctx' are being loaded by dir() on the loaded module
[DEBUG   ] The functions from module 'data' are being loaded by dir() on the loaded module
[DEBUG   ] The functions from module 'dateutils' are being loaded by dir() on the loaded module
[DEBUG   ] The functions from module 'debug' are being loaded by dir() on the loaded module
[DEBUG   ] The functions from module 'decorators' are being loaded by dir() on the loaded module
[DEBUG   ] The functions from module 'dictdiffer' are being loaded by dir() on the loaded module
[DEBUG   ] The functions from module 'dicttrim' are being loaded by dir() on the loaded module
[DEBUG   ] The functions from module 'dictupdate' are being loaded by dir() on the loaded module
[DEBUG   ] Override  __salt__: <module 'salt.loaded.int.utils.dns' from '/opt/saltstack/salt/lib/python3.10/site-packages/salt/utils/dns.py'>
[DEBUG   ] The functions from module 'dns' are being loaded by dir() on the loaded module
[DEBUG   ] The functions from module 'doc' are being loaded by dir() on the loaded module
[DEBUG   ] The functions from module 'entrypoints' are being loaded by dir() on the loaded module
[DEBUG   ] The functions from module 'environment' are being loaded by dir() on the loaded module
[DEBUG   ] The functions from module 'error' are being loaded by dir() on the loaded module
[DEBUG   ] The functions from module 'etcd_util' are being loaded by dir() on the loaded module
[DEBUG   ] The functions from module 'event' are being loaded by dir() on the loaded module
[DEBUG   ] The functions from module 'extend' are being loaded by dir() on the loaded module
[DEBUG   ] The functions from module 'extmods' are being loaded by dir() on the loaded module
[DEBUG   ] The functions from module 'filebuffer' are being loaded by dir() on the loaded module
[DEBUG   ] The functions from module 'files' are being loaded by dir() on the loaded module
[DEBUG   ] The functions from module 'find' are being loaded by dir() on the loaded module
[DEBUG   ] The functions from module 'fsutils' are being loaded by dir() on the loaded module
[DEBUG   ] The functions from module 'functools' are being loaded by dir() on the loaded module
[DEBUG   ] The functions from module 'gitfs' are being loaded by dir() on the loaded module
[DEBUG   ] The functions from module 'github' are being loaded by dir() on the loaded module
[DEBUG   ] The functions from module 'gzip_util' are being loaded by dir() on the loaded module
[DEBUG   ] The functions from module 'hashutils' are being loaded by dir() on the loaded module
[DEBUG   ] The functions from module 'http' are being loaded by dir() on the loaded module
[DEBUG   ] The functions from module 'iam' are being loaded by dir() on the loaded module
[DEBUG   ] Override  __salt__: <module 'salt.loaded.int.utils.icinga2' from '/opt/saltstack/salt/lib/python3.10/site-packages/salt/utils/icinga2.py'>
[DEBUG   ] The functions from module 'icinga2' are being loaded by dir() on the loaded module
[DEBUG   ] The functions from module 'immutabletypes' are being loaded by dir() on the loaded module
[DEBUG   ] The functions from module 'itertools' are being loaded by dir() on the loaded module
[DEBUG   ] The functions from module 'jid' are being loaded by dir() on the loaded module
[DEBUG   ] The functions from module 'jinja' are being loaded from the provided __all__ attribute
[DEBUG   ] The functions from module 'job' are being loaded by dir() on the loaded module
[DEBUG   ] The functions from module 'json' are being loaded by dir() on the loaded module
[DEBUG   ] The functions from module 'kickstart' are being loaded by dir() on the loaded module
[DEBUG   ] The functions from module 'kinds' are being loaded by dir() on the loaded module
[DEBUG   ] The functions from module 'lazy' are being loaded by dir() on the loaded module
[DEBUG   ] The functions from module 'listdiffer' are being loaded by dir() on the loaded module
[DEBUG   ] The functions from module 'locales' are being loaded by dir() on the loaded module
[DEBUG   ] Override  __salt__: <module 'salt.loaded.int.utils.mac_utils' from '/opt/saltstack/salt/lib/python3.10/site-packages/salt/utils/mac_utils.py'>
[DEBUG   ] The functions from module 'mako' are being loaded by dir() on the loaded module
[DEBUG   ] The functions from module 'master' are being loaded by dir() on the loaded module
[DEBUG   ] The functions from module 'mattermost' are being loaded by dir() on the loaded module
[DEBUG   ] The functions from module 'migrations' are being loaded by dir() on the loaded module
[DEBUG   ] The functions from module 'mine' are being loaded by dir() on the loaded module
[DEBUG   ] The functions from module 'minion' are being loaded by dir() on the loaded module
[DEBUG   ] The functions from module 'minions' are being loaded by dir() on the loaded module
[DEBUG   ] The functions from module 'mount' are being loaded by dir() on the loaded module
[DEBUG   ] The functions from module 'msazure' are being loaded by dir() on the loaded module
[DEBUG   ] The functions from module 'msgpack' are being loaded by dir() on the loaded module
[DEBUG   ] The functions from module 'namecheap' are being loaded by dir() on the loaded module
[DEBUG   ] The functions from module 'napalm' are being loaded by dir() on the loaded module
[DEBUG   ] The functions from module 'nb_popen' are being loaded by dir() on the loaded module
[DEBUG   ] The functions from module 'network' are being loaded by dir() on the loaded module
[DEBUG   ] The functions from module 'nxos' are being loaded by dir() on the loaded module
[DEBUG   ] The functions from module 'nxos_api' are being loaded by dir() on the loaded module
[DEBUG   ] The functions from module 'odict' are being loaded by dir() on the loaded module
[DEBUG   ] The functions from module 'openstack' are being loaded by dir() on the loaded module
[DEBUG   ] The functions from module 'oset' are being loaded by dir() on the loaded module
[DEBUG   ] The functions from module 'pagerduty' are being loaded by dir() on the loaded module
[DEBUG   ] The functions from module 'parsers' are being loaded by dir() on the loaded module
[DEBUG   ] The functions from module 'path' are being loaded by dir() on the loaded module
[DEBUG   ] The functions from module 'pkg' are being loaded by dir() on the loaded module
[DEBUG   ] The functions from module 'platform' are being loaded by dir() on the loaded module
[DEBUG   ] The functions from module 'powershell' are being loaded by dir() on the loaded module
[DEBUG   ] The functions from module 'preseed' are being loaded by dir() on the loaded module
[DEBUG   ] The functions from module 'process' are being loaded by dir() on the loaded module
[DEBUG   ] The functions from module 'profile' are being loaded by dir() on the loaded module
[DEBUG   ] The functions from module 'proxy' are being loaded by dir() on the loaded module
[DEBUG   ] The functions from module 'psutil_compat' are being loaded by dir() on the loaded module
[DEBUG   ] The functions from module 'pushover' are being loaded by dir() on the loaded module
[DEBUG   ] The functions from module 'pycrypto' are being loaded by dir() on the loaded module
[DEBUG   ] The functions from module 'pydsl' are being loaded by dir() on the loaded module
[DEBUG   ] The functions from module 'pyobjects' are being loaded by dir() on the loaded module
[DEBUG   ] The functions from module 'reactor' are being loaded by dir() on the loaded module
[DEBUG   ] The functions from module 'reclass' are being loaded by dir() on the loaded module
[DEBUG   ] The functions from module 'roster_matcher' are being loaded by dir() on the loaded module
[DEBUG   ] The functions from module 'rsax931' are being loaded by dir() on the loaded module
[DEBUG   ] The functions from module 's3' are being loaded by dir() on the loaded module
[DEBUG   ] The functions from module 'saltclass' are being loaded by dir() on the loaded module
[DEBUG   ] The functions from module 'sanitizers' are being loaded by dir() on the loaded module
[DEBUG   ] The functions from module 'schedule' are being loaded by dir() on the loaded module
[DEBUG   ] The functions from module 'schema' are being loaded by dir() on the loaded module
[DEBUG   ] The functions from module 'sdb' are being loaded by dir() on the loaded module
[DEBUG   ] The functions from module 'slack' are being loaded by dir() on the loaded module
[DEBUG   ] The functions from module 'smb' are being loaded by dir() on the loaded module
[DEBUG   ] The functions from module 'smtp' are being loaded by dir() on the loaded module
[DEBUG   ] The functions from module 'ssdp' are being loaded by dir() on the loaded module
[DEBUG   ] The functions from module 'ssh' are being loaded by dir() on the loaded module
[DEBUG   ] The functions from module 'state' are being loaded by dir() on the loaded module
[DEBUG   ] The functions from module 'stringio' are being loaded by dir() on the loaded module
[DEBUG   ] The functions from module 'stringutils' are being loaded by dir() on the loaded module
[DEBUG   ] The functions from module 'systemd' are being loaded by dir() on the loaded module
[DEBUG   ] The functions from module 'templates' are being loaded by dir() on the loaded module
[DEBUG   ] The functions from module 'textformat' are being loaded by dir() on the loaded module
[DEBUG   ] The functions from module 'thin' are being loaded by dir() on the loaded module
[DEBUG   ] The functions from module 'timed_subprocess' are being loaded by dir() on the loaded module
[DEBUG   ] The functions from module 'timeout' are being loaded by dir() on the loaded module
[DEBUG   ] The functions from module 'timeutil' are being loaded by dir() on the loaded module
[DEBUG   ] The functions from module 'url' are being loaded by dir() on the loaded module
[DEBUG   ] The functions from module 'user' are being loaded by dir() on the loaded module
[DEBUG   ] The functions from module 'validate' are being loaded by dir() on the loaded module
[DEBUG   ] The functions from module 'value' are being loaded by dir() on the loaded module
[DEBUG   ] The functions from module 'vault' are being loaded by dir() on the loaded module
[DEBUG   ] The functions from module 'verify' are being loaded by dir() on the loaded module
[DEBUG   ] The functions from module 'versions' are being loaded by dir() on the loaded module
[DEBUG   ] The functions from module 'virt' are being loaded by dir() on the loaded module
[DEBUG   ] The functions from module 'virtualbox' are being loaded by dir() on the loaded module
[DEBUG   ] The functions from module 'vt' are being loaded by dir() on the loaded module
[DEBUG   ] The functions from module 'vt_helper' are being loaded by dir() on the loaded module
[DEBUG   ] The functions from module 'x509' are being loaded by dir() on the loaded module
[DEBUG   ] The functions from module 'xdg' are being loaded by dir() on the loaded module
[DEBUG   ] The functions from module 'xmlutil' are being loaded by dir() on the loaded module
[DEBUG   ] The functions from module 'yaml' are being loaded by dir() on the loaded module
[DEBUG   ] The functions from module 'yamldumper' are being loaded from the provided __all__ attribute
[DEBUG   ] The functions from module 'yamlencoding' are being loaded by dir() on the loaded module
[DEBUG   ] The functions from module 'yamllint' are being loaded by dir() on the loaded module
[DEBUG   ] The functions from module 'yamlloader' are being loaded from the provided __all__ attribute
[DEBUG   ] The functions from module 'yamlloader_old' are being loaded from the provided __all__ attribute
[DEBUG   ] The functions from module 'yast' are being loaded by dir() on the loaded module
[DEBUG   ] The functions from module 'zeromq' are being loaded by dir() on the loaded module
[DEBUG   ] The functions from module 'zfs' are being loaded by dir() on the loaded module
[DEBUG   ] Override  __utils__: <module 'salt.loaded.int.clouds.azurerm' from '/opt/saltstack/salt/lib/python3.10/site-packages/saltext/azurerm/clouds/azurerm.py'>
[DEBUG   ] The functions from module 'azurerm' are being loaded by dir() on the loaded module
[DEBUG   ] The functions from module 'lxc' are being loaded by dir() on the loaded module
[DEBUG   ] The functions from module 'saltify' are being loaded by dir() on the loaded module
[DEBUG   ] The functions from module 'vagrant' are being loaded by dir() on the loaded module
[DEBUG   ] Could not LazyLoad parallels.avail_sizes: 'parallels' __virtual__ returned False
[DEBUG   ] LazyLoaded parallels.avail_locations
[DEBUG   ] LazyLoaded proxmox.avail_sizes
[INFO    ] No environment configuration found.
[ERROR   ] Failed to get the output of 'azurerm.avail_locations()': azure.identity._credentials.managed_identity.ManagedIdentityCredential() got multiple values for keyword argument 'client_id'
Traceback (most recent call last):
  File "/opt/saltstack/salt/lib/python3.10/site-packages/salt/cloud/__init__.py", line 823, in location_list
    data[alias][driver] = self.clouds[fun]()
  File "/opt/saltstack/salt/lib/python3.10/site-packages/salt/loader/lazy.py", line 159, in __call__
    ret = self.loader.run(run_func, *args, **kwargs)
  File "/opt/saltstack/salt/lib/python3.10/site-packages/salt/loader/lazy.py", line 1245, in run
    return self._last_context.run(self._run_as, _func_or_method, *args, **kwargs)
  File "/opt/saltstack/salt/lib/python3.10/site-packages/salt/loader/lazy.py", line 1260, in _run_as
    return _func_or_method(*args, **kwargs)
  File "/opt/saltstack/salt/lib/python3.10/site-packages/saltext/azurerm/clouds/azurerm.py", line 335, in avail_locations
    resconn = get_conn(client_type="resource")
  File "/opt/saltstack/salt/lib/python3.10/site-packages/saltext/azurerm/clouds/azurerm.py", line 260, in get_conn
    client = saltext.azurerm.utils.azurerm.get_client(client_type=client_type, **conn_kwargs)
  File "/opt/saltstack/salt/lib/python3.10/site-packages/saltext/azurerm/utils/azurerm.py", line 161, in get_client
    credentials, subscription_id, cloud_env = _determine_auth(**kwargs)
  File "/opt/saltstack/salt/lib/python3.10/site-packages/saltext/azurerm/utils/azurerm.py", line 102, in _determine_auth
    credentials = DefaultAzureCredential(authority=authority, **kwargs)
  File "/opt/saltstack/salt/lib/python3.10/site-packages/azure/identity/_credentials/default.py", line 126, in __init__
    credentials.append(ManagedIdentityCredential(client_id=managed_identity_client_id, **kwargs))
TypeError: azure.identity._credentials.managed_identity.ManagedIdentityCredential() got multiple values for keyword argument 'client_id'
[DEBUG   ] The functions from module 'nested' are being loaded by dir() on the loaded module
[DEBUG   ] LazyLoaded nested.output
azurearm-FranceCentral:
    ----------

```

**Screenshots**

**Versions Report**
<details><summary>salt --versions-report</summary>
(Provided by running salt --versions-report. Please also mention any differences in master/minion versions.)

```yaml
# salt --versions-report
Salt Version:
            Salt: 3006.7
 
Python Version:
          Python: 3.10.13 (main, Feb 19 2024, 03:31:20) [GCC 11.2.0]
 
Dependency Versions:
            cffi: 1.14.6
        cherrypy: unknown
        dateutil: 2.8.1
       docker-py: Not Installed
           gitdb: Not Installed
       gitpython: Not Installed
          Jinja2: 3.1.3
         libgit2: 1.5.0
    looseversion: 1.0.2
        M2Crypto: Not Installed
            Mako: 1.2.4
         msgpack: 1.0.2
    msgpack-pure: Not Installed
    mysql-python: Not Installed
       packaging: 22.0
       pycparser: 2.21
        pycrypto: Not Installed
    pycryptodome: 3.19.1
          pygit2: 1.11.1
    python-gnupg: 0.4.8
          PyYAML: 6.0.1
           PyZMQ: 23.2.0
          relenv: 0.15.1
           smmap: Not Installed
         timelib: 0.2.4
         Tornado: 4.5.3
             ZMQ: 4.3.4
 
Salt Extensions:
 saltext.azurerm: 4.0.1
 
System Versions:
            dist: debian 10 buster
          locale: utf-8
         machine: x86_64
         release: 4.19.0-26-cloud-amd64
          system: Linux
         version: Debian GNU/Linux 10 buster
```
</details>

**Additional context**

Thanks for help

**Comment by arkpoah** [comment]
Just saw #46..
